import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import JSZip from 'npm:jszip@3.10.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const fileUrl = body.fileUrl;
    
    if (!fileUrl) {
      return Response.json({ error: 'Missing fileUrl parameter' }, { status: 400 });
    }

    console.log("📦 Downloading archive from:", fileUrl);
    
    const response = await fetch(fileUrl);
    
    if (!response.ok) {
      return Response.json({ error: `Failed to fetch file: ${response.status}` }, { status: 400 });
    }
    
    const blob = await response.blob();
    console.log("📦 Archive size:", blob.size, "bytes");

    const zip = await JSZip.loadAsync(blob);
    console.log("📦 ZIP loaded successfully");
    
    const data = {
      profile: { name: "", email: "" },
      posts: [],
      friends: [],
      messages: [],
      photos: [],
      photoFiles: {},
      videoFiles: {},
      comments: [],
      reels: [],
      videos: [],
      checkins: [],
      likes: [],
      events: [],
      reviews: [],
      groups: [],
      marketplace: [],
      allData: {}
    };

    // Helper to decode Facebook's encoded text
    const decodeFacebookText = (text) => {
      if (!text) return "";
      return text
        .replace(/\\u00([0-9a-fA-F]{2})/g, (match, hex) => String.fromCharCode(parseInt(hex, 16)))
        .replace(/&#x([0-9a-fA-F]+);/g, (match, hex) => String.fromCharCode(parseInt(hex, 16)))
        .replace(/&#039;/g, "'")
        .replace(/&quot;/g, '"')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&nbsp;/g, ' ')
        .trim();
    };

    // PHASE 1: Extract media files (limit to first 50 photos and 10 videos to avoid timeout)
    console.log("📸 Phase 1: Extracting media...");
    let photoCount = 0, videoCount = 0;

    for (const [path, file] of Object.entries(zip.files)) {
      if (file.dir) continue;

      // Photos (limit to 50)
      if (photoCount < 50 && path.match(/\.(jpg|jpeg|png|gif|webp)$/i) && !path.includes('icon')) {
        try {
          const imageData = await file.async("base64");
          const ext = path.split('.').pop().toLowerCase();
          const mimeType = {
            'jpg': 'image/jpeg', 'jpeg': 'image/jpeg',
            'png': 'image/png', 'gif': 'image/gif',
            'webp': 'image/webp'
          }[ext] || 'image/jpeg';

          data.photoFiles[path] = `data:${mimeType};base64,${imageData}`;
          data.photos.push({ path, filename: path.split('/').pop(), timestamp: "" });
          photoCount++;
        } catch (err) {
          console.error(`Failed to extract photo ${path}`);
        }
      }

      // Videos (limit to 10)
      if (videoCount < 10 && path.match(/\.(mp4|webm|mov)$/i)) {
        try {
          const videoData = await file.async("base64");
          const ext = path.split('.').pop().toLowerCase();
          const mimeType = { 'mp4': 'video/mp4', 'webm': 'video/webm', 'mov': 'video/quicktime' }[ext] || 'video/mp4';

          data.videoFiles[path] = `data:${mimeType};base64,${videoData}`;
          data.videos.push({ path, filename: path.split('/').pop(), timestamp: "" });
          videoCount++;
        } catch (err) {
          console.error(`Failed to extract video ${path}`);
        }
      }
    }

    console.log(`✅ Extracted ${photoCount} photos, ${videoCount} videos`);

    // PHASE 2: Parse ALL HTML and JSON files
    console.log("📄 Phase 2: Parsing archive files...");
    
    for (const [path, file] of Object.entries(zip.files)) {
      if (file.dir) continue;
      
      try {
        const content = await file.async("text");
        
        // Extract profile name
        if (!data.profile.name) {
          const nameMatch = content.match(/Generated by ([^<\n]+) on/i);
          if (nameMatch) {
            data.profile.name = decodeFacebookText(nameMatch[1]);
          }
        }
        
        // === POSTS (HTML) - Facebook uses <section> elements ===
        if (path.endsWith('.html') && (path.includes('posts') || path.includes('album'))) {
          const sections = content.matchAll(/<section[^>]*>(.*?)<\/section>/gs);
          
          for (const section of sections) {
            const html = section[1];
            
            // Extract h2 (post title/type)
            const h2Match = html.match(/<h2[^>]*id="[^"]*">([^<]+)<\/h2>/);
            const title = h2Match ? decodeFacebookText(h2Match[1]) : "";
            
            // Extract actual post content from _2pin div
            const contentMatches = html.matchAll(/<div class="_2pin"><div>([^<]+)<\/div>/g);
            const contents = [];
            for (const m of contentMatches) {
              contents.push(decodeFacebookText(m[1]));
            }
            
            // Extract timestamp
            const timeMatch = html.match(/<div class="_a72d">([^<]+)<\/div>/);
            const timestamp = timeMatch ? decodeFacebookText(timeMatch[1]) : "";
            
            // Check for media
            const imgMatch = html.match(/href="([^"]+\.(jpg|jpeg|png|gif))"/i);
            const photo_url = imgMatch ? (data.photoFiles[imgMatch[1]] || null) : null;
            
            // Combine title and content
            const postText = [title, ...contents].filter(t => t).join(' - ');
            
            if (postText.length >= 10) {
              data.posts.push({
                text: postText,
                timestamp,
                photo_url,
                likes_count: 0,
                comments_count: 0,
                comments: []
              });
            }
          }
        }
        
        // === COMMENTS (HTML) ===
        if (path.endsWith('.html') && path.match(/comments/i)) {
          const sections = content.matchAll(/<section[^>]*>(.*?)<\/section>/gs);
          
          for (const section of sections) {
            const html = section[1];
            
            // Extract comment text
            const contentMatch = html.match(/<div class="_2pin"><div>([^<]+)<\/div>/);
            const text = contentMatch ? decodeFacebookText(contentMatch[1]) : "";
            
            // Extract timestamp
            const timeMatch = html.match(/<div class="_a72d">([^<]+)<\/div>/);
            const timestamp = timeMatch ? decodeFacebookText(timeMatch[1]) : "";
            
            if (text.length >= 10) {
              data.comments.push({ text, timestamp });
            }
          }
        }
        
        // === FRIENDS (HTML) ===
        if (path.endsWith('.html') && path.match(/friends/i)) {
          const sections = content.matchAll(/<section[^>]*>(.*?)<\/section>/gs);
          
          for (const section of sections) {
            const html = section[1];
            
            // Friend name is in h2
            const nameMatch = html.match(/<h2[^>]*>([^<]+)<\/h2>/);
            if (nameMatch) {
              const name = decodeFacebookText(nameMatch[1]);
              if (name.length > 2 && name.length < 100 && 
                  !name.match(/Friends|Facebook|Your friends/i) &&
                  !data.friends.find(f => f.name === name)) {
                
                const timeMatch = html.match(/<div class="_a72d">([^<]+)<\/div>/);
                const date_added = timeMatch ? decodeFacebookText(timeMatch[1]) : "";
                
                data.friends.push({ name, date_added });
              }
            }
          }
        }
        
        // === MESSAGES (JSON) ===
        if (path.endsWith('.json') && path.includes('message')) {
          try {
            const json = JSON.parse(content);
            if (json.messages && Array.isArray(json.messages)) {
              const convoName = decodeFacebookText(json.title || "");
              const msgs = json.messages.map(m => ({
                sender: decodeFacebookText(m.sender_name || "Unknown"),
                text: decodeFacebookText(m.content || ""),
                timestamp: m.timestamp_ms ? new Date(m.timestamp_ms).toLocaleString() : "",
                timestamp_ms: m.timestamp_ms || 0
              })).filter(m => m.text);
              
              if (msgs.length > 0) {
                data.messages.push({
                  conversation_with: convoName,
                  messages: msgs,
                  lastMessageTimestamp: msgs[0]?.timestamp_ms || 0,
                  totalMessages: msgs.length
                });
              }
            }
          } catch (e) {}
        }
        
        // === JSON Posts/Comments ===
        if (path.endsWith('.json') && (path.includes('posts') || path.includes('comment'))) {
          try {
            const json = JSON.parse(content);
            
            const postsArray = Array.isArray(json) ? json : (json.posts || []);
            postsArray.forEach(post => {
              const postData = post.data?.[0] || post;
              const text = decodeFacebookText(postData.post || postData.title || "");
              const timestamp = postData.timestamp ? new Date(postData.timestamp * 1000).toLocaleString() : "";
              
              if (text && text.length > 5) {
                data.posts.push({
                  text,
                  timestamp,
                  photo_url: null,
                  likes_count: 0,
                  comments_count: 0,
                  comments: []
                });
              }
            });
            
            const commentsArray = json.comments || [];
            commentsArray.forEach(comment => {
              const commentData = comment.data?.[0] || comment;
              const text = decodeFacebookText(commentData.comment?.comment || commentData.text || "");
              const timestamp = commentData.timestamp ? new Date(commentData.timestamp * 1000).toLocaleString() : "";
              
              if (text && text.length > 5) {
                data.comments.push({ text, timestamp });
              }
            });
          } catch (e) {}
        }
        
        // === FRIENDS (JSON) ===
        if (path.endsWith('.json') && path.includes('friends')) {
          try {
            const json = JSON.parse(content);
            const friendsList = json.friends_v2 || json.friends || [];
            
            friendsList.forEach(f => {
              const name = decodeFacebookText(f.name || f.title || "");
              if (name.length > 2 && !data.friends.find(fr => fr.name === name)) {
                data.friends.push({ 
                  name, 
                  date_added: f.timestamp ? new Date(f.timestamp * 1000).toLocaleDateString() : ""
                });
              }
            });
          } catch (e) {}
        }
        
      } catch (err) {
        console.error(`Error: ${path}`);
      }
    }

    // Deduplicate
    data.friends = [...new Map(data.friends.map(f => [f.name.toLowerCase(), f])).values()];
    data.messages.sort((a, b) => (b.lastMessageTimestamp || 0) - (a.lastMessageTimestamp || 0));

    console.log("\n✅ EXTRACTION COMPLETE:");
    console.log(`  👤 Profile: ${data.profile.name || 'Unknown'}`);
    console.log(`  📝 Posts: ${data.posts.length}`);
    console.log(`  💬 Comments: ${data.comments.length}`);
    console.log(`  👥 Friends: ${data.friends.length}`);
    console.log(`  💌 Messages: ${data.messages.length} conversations`);
    console.log(`  📸 Photos: ${Object.keys(data.photoFiles).length}`);
    console.log(`  🎥 Videos: ${Object.keys(data.videoFiles).length}`);

    return Response.json(data);
    
  } catch (error) {
    console.error("Error:", error);
    return Response.json({ error: error.message || 'Failed to extract archive' }, { status: 500 });
  }
});