import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import JSZip from 'npm:jszip@3.10.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const fileUrl = body.fileUrl;
    
    if (!fileUrl) {
      return Response.json({ error: 'Missing fileUrl parameter' }, { status: 400 });
    }

    console.log("📦 Downloading archive from:", fileUrl);
    
    const response = await fetch(fileUrl);
    
    if (!response.ok) {
      return Response.json({ error: `Failed to fetch file: ${response.status}` }, { status: 400 });
    }
    
    const blob = await response.blob();
    console.log("📦 Archive size:", blob.size, "bytes");

    const zip = await JSZip.loadAsync(blob);
    console.log("📦 ZIP loaded successfully");
    
    const data = {
      profile: { name: "", email: "" },
      posts: [],
      friends: [],
      messages: [],
      photos: [],
      photoFiles: {},
      videoFiles: {},
      comments: [],
      reels: [],
      videos: [],
      checkins: [],
      likes: [],
      events: [],
      reviews: [],
      groups: [],
      marketplace: [],
      allData: {}
    };

    // Helper to decode Facebook's encoded text
    const decodeFacebookText = (text) => {
      return text
        .replace(/\\u00([0-9a-fA-F]{2})/g, (match, hex) => String.fromCharCode(parseInt(hex, 16)))
        .replace(/&#x([0-9a-fA-F]+);/g, (match, hex) => String.fromCharCode(parseInt(hex, 16)))
        .replace(/&quot;/g, '"')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&nbsp;/g, ' ');
    };

    // PHASE 1: Extract all media files (photos and videos)
    console.log("📸 Phase 1: Extracting photos and videos...");
    let photoCount = 0, videoCount = 0;

    for (const [path, file] of Object.entries(zip.files)) {
      if (file.dir) continue;

      // Extract photos
      if (path.match(/\.(jpg|jpeg|png|gif|webp|bmp)$/i) && !path.includes('icon')) {
        try {
          const imageData = await file.async("base64");
          const ext = path.split('.').pop().toLowerCase();
          const mimeType = {
            'jpg': 'image/jpeg', 'jpeg': 'image/jpeg',
            'png': 'image/png', 'gif': 'image/gif',
            'webp': 'image/webp', 'bmp': 'image/bmp'
          }[ext] || 'image/jpeg';

          data.photoFiles[path] = `data:${mimeType};base64,${imageData}`;
          data.photos.push({ path, filename: path.split('/').pop(), timestamp: "" });
          photoCount++;
        } catch (err) {
          console.error(`❌ Failed to extract photo ${path}:`, err.message);
        }
      }

      // Extract videos
      if (path.match(/\.(mp4|mov|avi|mkv|webm|m4v)$/i)) {
        try {
          const videoData = await file.async("base64");
          const ext = path.split('.').pop().toLowerCase();
          const mimeType = {
            'mp4': 'video/mp4', 'webm': 'video/webm',
            'mov': 'video/quicktime', 'avi': 'video/x-msvideo'
          }[ext] || 'video/mp4';

          data.videoFiles[path] = `data:${mimeType};base64,${videoData}`;
          data.videos.push({ path, filename: path.split('/').pop(), timestamp: "" });
          videoCount++;
        } catch (err) {
          console.error(`❌ Failed to extract video ${path}:`, err.message);
        }
      }
    }

    console.log(`✅ Extracted ${photoCount} photos, ${videoCount} videos`);

    // PHASE 2: Parse HTML files - Facebook stores data in HTML, NOT JSON!
    console.log("📄 Phase 2: Parsing HTML files...");

    for (const [path, file] of Object.entries(zip.files)) {
      if (file.dir || !path.endsWith('.html')) continue;

      try {
        const content = await file.async("text");

        // Extract profile name
        if (!data.profile.name) {
          const nameMatch = content.match(/Generated by ([^<\n]+) on/i);
          if (nameMatch) {
            data.profile.name = decodeFacebookText(nameMatch[1].trim());
            console.log(`👤 Profile: ${data.profile.name}`);
          }
        }

        // POSTS - stored in HTML files like "your_posts__check_ins__photos_and_videos_1.html"
        if (path.includes('your_posts') || path.includes('your_facebook_activity/posts/')) {
          // Facebook posts are in div elements within the body
          const divMatches = content.matchAll(/<div[^>]*>(.*?)<\/div>/gs);

          for (const match of divMatches) {
            const divContent = match[1];

            // Extract post text - look for actual content (not CSS/metadata)
            const textMatch = divContent.match(/>([^<]{20,})</);
            if (!textMatch) continue;

            let postText = decodeFacebookText(textMatch[1].trim());

            // Skip if it's CSS or metadata
            if (postText.match(/font-family|background|margin|padding|color:/i)) continue;
            if (postText.length < 10) continue;

            // Extract timestamp
            const dateMatch = divContent.match(/(\w+ \d{1,2}, \d{4})/);
            const timestamp = dateMatch ? dateMatch[1] : "";

            // Check for associated media
            const mediaMatch = divContent.match(/media\/(.*?)\.(jpg|png|mp4)/i);
            let photo_url = null;
            if (mediaMatch) {
              const mediaPath = `your_facebook_activity/posts/media/${mediaMatch[1]}.${mediaMatch[2]}`;
              photo_url = data.photoFiles[mediaPath] || null;
            }

            if (postText.length >= 10) {
              data.posts.push({
                text: postText,
                timestamp,
                photo_url,
                likes_count: 0,
                comments_count: 0,
                comments: []
              });
            }
          }
        }

        // COMMENTS - stored in comments HTML files
        if (path.includes('comment')) {
          const divMatches = content.matchAll(/<div[^>]*>(.*?)<\/div>/gs);

          for (const match of divMatches) {
            const divContent = match[1];
            const textMatch = divContent.match(/>([^<]{15,})</);
            if (!textMatch) continue;

            let commentText = decodeFacebookText(textMatch[1].trim());
            if (commentText.match(/font-family|background|margin/i)) continue;
            if (commentText.length < 10) continue;

            const dateMatch = divContent.match(/(\w+ \d{1,2}, \d{4})/);
            const timestamp = dateMatch ? dateMatch[1] : "";

            data.comments.push({ text: commentText, timestamp });
          }
        }

        // FRIENDS - stored in connections/friends HTML files
        if (path.includes('friends') && path.includes('.html')) {
          const listMatches = content.matchAll(/<li[^>]*>([^<]+)<\/li>/g);
          for (const match of listMatches) {
            const name = decodeFacebookText(match[1].trim());
            if (name.length > 2 && name.length < 100 && 
                !data.friends.find(f => f.name === name)) {
              data.friends.push({ name, date_added: "" });
            }
          }
        }

      } catch (err) {
        console.error(`Error processing ${path}:`, err.message);
      }
    }

    // PHASE 3: Process JSON files (messages, etc)
    console.log("📄 Phase 3: Processing JSON files...");

    for (const [path, file] of Object.entries(zip.files)) {
      if (file.dir || !path.endsWith('.json')) continue;

      try {
        const content = await file.async("text");
        const json = JSON.parse(content);

        // MESSAGES
        if (json.messages && Array.isArray(json.messages)) {
          const convoName = json.title || path.split('/').pop().replace('.json', '').replace(/_/g, ' ');
          const msgs = json.messages.map(m => ({
            sender: m.sender_name || "Unknown",
            text: m.content || "",
            timestamp: m.timestamp_ms ? new Date(m.timestamp_ms).toLocaleString() : "",
            timestamp_ms: m.timestamp_ms || 0
          })).filter(m => m.text);

          if (msgs.length > 0) {
            data.messages.push({
              conversation_with: decodeFacebookText(convoName),
              messages: msgs,
              lastMessageTimestamp: msgs[0]?.timestamp_ms || 0,
              totalMessages: msgs.length
            });
          }
        }

        // FRIENDS from JSON
        if (json.friends_v2 || json.friends) {
          const friendsList = json.friends_v2 || json.friends;
          friendsList.forEach(f => {
            const name = f.name || f.title || "";
            if (name.length > 2 && !data.friends.find(fr => fr.name === name)) {
              data.friends.push({ 
                name: decodeFacebookText(name), 
                date_added: f.timestamp ? new Date(f.timestamp * 1000).toLocaleDateString() : ""
              });
            }
          });
        }

      } catch (e) {}
    }

    // Deduplicate and clean up
    data.friends = [...new Map(data.friends.map(f => [f.name.toLowerCase(), f])).values()];
    data.groups = [...new Map(data.groups.map(g => [g.name.toLowerCase(), g])).values()];
    data.messages.sort((a, b) => (b.lastMessageTimestamp || 0) - (a.lastMessageTimestamp || 0));

    console.log("\n✅ EXTRACTION COMPLETE:");
    console.log(`  👤 Profile: ${data.profile.name || 'Unknown'}`);
    console.log(`  👥 Friends: ${data.friends.length}`);
    console.log(`  📝 Posts: ${data.posts.length}`);
    console.log(`  💬 Messages: ${data.messages.length} conversations`);
    console.log(`  📸 Photos: ${Object.keys(data.photoFiles).length} (${data.photos.length} metadata)`);
    console.log(`  🎥 Videos: ${Object.keys(data.videoFiles).length}`);
    console.log(`  💭 Comments: ${data.comments.length}`);
    console.log(`  👥 Groups: ${data.groups.length}`);

    return Response.json(data);
    
  } catch (error) {
    console.error("Error:", error);
    return Response.json({ error: error.message || 'Failed to extract archive' }, { status: 500 });
  }
});